name: subscribe update

on:
  push:
      branches: [ "main" ]
  schedule:
    - cron: '20 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #- name: setup rust and go
      #  run:  |
      #    sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
      - run:  |
          cargo --version
          rustc --version
          go version


      
      - name: make env
        run: |
          git --version
          # echo ${{ secrets.ROMOTE_REPO }}
          mkdir orepo
          cd orepo
        
      - uses: actions/checkout@v3
        with:
          repository: 'apple280/fly'
          path: '${{ github.workspace }}/orepo/v2tool'
          ref:  'main'

      - uses: actions/checkout@v3
        with:
          repository: '${{ secrets.ROMOTE_REPO }}'
          token: '${{ secrets.PERSONAL_TOKEN }}'
          path: '${{ github.workspace }}/orepo/v2speed'

      - name: build
        run: |
          cd ${{ github.workspace }}/orepo/v2tool
          # ls
          # $bin = "${{ github.workspace }}/target/release"

          go mod tidy
          go build -o ${{ github.workspace }}/orepo/v2speed/target/release/v2tool

          cd ${{ github.workspace }}/orepo/v2speed
          cargo build --release

          chmod 777 run.sh
          mv run.sh ${{ github.workspace }}/orepo/v2speed/target/release
          
      - name: run
        run: |
          cd ${{ github.workspace }}/orepo/v2speed/target/release
          ./run.sh

          mv ${{ github.workspace }}/orepo/v2speed/target/release/out.png ${{ github.workspace }}/traffic.png
          
          mv ${{ github.workspace }}/orepo/v2speed/target/release/data/v2_main ${{ github.workspace }}/v2
          mv ${{ github.workspace }}/orepo/v2speed/target/release/data/clash_main ${{ github.workspace }}/clash
          mv ${{ github.workspace }}/orepo/v2speed/target/release/data/README.md_main ${{ github.workspace }}/README.md

      
      - name: commit changes
        run:  |
          cd ${{ github.workspace }}
          git config user.email "github-actions+bot+4fas4f15@no-reply.github.com"
          git config user.name "actions"
          git add .
          git commit -m "🚀 $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

      - name: checkout speed
        uses: actions/checkout@v3
        with:
          ref:  speed
          path: 'orepo/speed'
      - name: commit and push speed
        run:  |
          cd ${{ github.workspace }}/orepo/speed
          rm v2
          rm clash
          rm README.md

          mv ${{ github.workspace }}/orepo/v2speed/target/release/data/v2_speed ${{ github.workspace }}/orepo/speed/v2
          mv ${{ github.workspace }}/orepo/v2speed/target/release/data/clash_speed ${{ github.workspace }}/orepo/speed/clash
          mv ${{ github.workspace }}/orepo/v2speed/target/release/data/README.md_speed ${{ github.workspace }}/orepo/speed/README.md
          
          git config user.email "github-actions+bot+545465hgf@no-reply.github.com"
          git config user.name "actions"
          git add .
          git commit -m "♻ $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
          git push https://${{secrets.PERSONAL_TOKEN}}@github.com/ts-sf/fly.git speed
