name: subscribe update

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '20 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
      - run: |
          cargo --version
          rustc --version
          go version
      
      - name: make env
        run: |
          git --version
          mkdir orepo
          cd orepo
        
      - uses: actions/checkout@v3
        with:
          repository: 'apple280/fly'
          path: '${{ github.workspace }}/orepo/v2tool'
          ref:  'main'

      - uses: actions/checkout@v3
        with:
          repository: '${{ secrets.ROMOTE_REPO }}'
          token: '${{ secrets.PERSONAL_TOKEN }}'
          path: '${{ github.workspace }}/orepo/v2speed'

      - name: build
        run: |
          cd ${{ github.workspace }}/orepo/v2tool
          if [ -f "go.mod" ]; then
            go mod tidy
            go build -o ${{ github.workspace }}/orepo/v2speed/target/release/v2tool
          else
            echo "go.mod does not exist in the v2tool directory"
            exit 1
          fi
          
          cd ${{ github.workspace }}/orepo/v2speed
          if [ -f "Cargo.toml" ]; then
            cargo build --release
          else
            echo "Cargo.toml does not exist in the v2speed directory"
            exit 1
          fi
          
          chmod 777 run.sh
          mv run.sh ${{ github.workspace }}/orepo/v2speed/target/release
          
      - name: run
        run: |
          cd ${{ github.workspace }}/orepo/v2speed/target/release
          ./run.sh
          mv out.png ${{ github.workspace }}/traffic.png
          mv data/v2_main ${{ github.workspace }}/v2
          mv data/clash_main ${{ github.workspace }}/clash
          mv data/README.md_main ${{ github.workspace }}/README.md
      
      - name: commit changes
        run: |
          cd ${{ github.workspace }}
          git config user.email "github-actions+bot@no-reply.github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "🚀 $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          
      - name: checkout speed
        uses: actions/checkout@v3
        with:
          ref:  speed
          path: 'orepo/speed'
          
      - name: commit and push speed
        run: |
          cd ${{ github.workspace }}/orepo/speed
          rm v2 clash README.md
          mv ${{ github.workspace }}/v2 ${{ github.workspace }}/orepo/speed/v2
          mv ${{ github.workspace }}/clash ${{ github.workspace }}/orepo/speed/clash
          mv ${{ github.workspace }}/README.md ${{ github.workspace }}/orepo/speed/README.md
          
          git config user.email "github-actions+bot@no-reply.github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "♻ $(date -d '-8 hours ago' "+%Y-%m-%d %H:%M:%S")"
          git push https://${{ secrets.PERSONAL_TOKEN }}@github.com/apple280/fly.git speed
